import { defineConfig } from "umi";

export default defineConfig({
  deadCode: {},
  dva: {},
  antd: {},
  model: {},
  theme: {},
  access: {},
  request: {},
  crossorigin: {},
  initialState: {},
  styledComponents: {},
  layout: {
    title: "",
  },
  outputPath: "dist",
  npmClient: "yarn",
  proxy: {
    "/api": {
      target: "http://192.168.0.130:6789/",
      changeOrigin: true,
    },
  },
  define: {
    URL:
      process.env.NODE_ENV === "development"
        ? "http://192.168.0.130:6789/api/graphql"
        : "http://192.168.0.130:6790/api/graphql",
    RC_URL:
      process.env.NODE_ENV === "development"
        ? "http://192.168.0.134:4000"
        : "http://192.168.0.133:3000",
    OSS_URL: "https://ckmro.oss-cn-shanghai.aliyuncs.com",
  },
  routes: [
    {
      path: "/",
      redirect: "/login",
    },
    {
      name: " ",
      path: "/login",
      component: "@/pages/Login/index",
      layout: false,
      hideInMenu: true,
    },
    {
      path: "/",
      component: "@/layouts/index",
      routes: [],
    },
    {
      name: " ",
      path: "/intro",
      component: "./Login/intro",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/login/basic",
      component: "./Login/basic",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/login/reset",
      component: "./Login/reset",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/login/changepwd",
      component: "./Login/change",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/login/realNameAuthentication",
      component: "./Login/realNameAuthentication",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/login/loginInfo",
      component: "./Login/loginInfo",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/inquiry",
      component: "./InquiryAndOffer",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/InquiryAndOffer/detail",
      component: "./InquiryAndOffer/detail",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/InquiryAndOffer/one",
      component: "./InquiryAndOffer/one",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/room",
      component: "./Room",
      icon: "Message",
    },
    {
      name: " ",
      path: "/contact",
      component: "./Contact",
      icon: "Team",
    },
    {
      name: " ",
      path: "/contact/updateTags",
      layout: false,
      component: "@/pages/Contact/UpdateTags",
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/workstand",
      component: "./Workstand",
      icon: "Appstore",
    },
    {
      name: " ",
      path: "/settings",
      component: "./Settings",
      layout: false,
      hideInMenu: true,
      icon: "Setting",
    },
    {
      name: " ",
      path: "/enterpriseCertification",
      component: "./EnterpriseCertification",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/add",
      component: "./Contact/Add",
      layout: false,
      hideInMenu: true,
    },
    {
      name: " ",
      path: "/workstand/InquiryEdit",
      component: "./Workstand/Inquiry/EditInquiry",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/workstand/InquiryCustomer",
      component: "./Workstand/Inquiry/CustomerInquiry",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/workstand/InquiryMy",
      component: "./Workstand/Inquiry/MyInquiry",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/workstand/OfferGo",
      component: "./Workstand/Offer/GoOffer",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/workstand/OfferMananger",
      component: "./Workstand/Offer/OfferMananger",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/workstand/OfferShare",
      component: "./Workstand/Offer/ShareOffer",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/ContractList",
      component: "./Workstand/Order/Contract/ContractListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/ContractDetail",
      component: "./Workstand/Order/Contract/ContractDetailView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/CollectionList",
      component: "./Workstand/Order/Money/CollectionListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/PaymentList",
      component: "./Workstand/Order/Money/PaymentListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/ReceiveGoodsList",
      component: "./Workstand/Order/Goods/ReceiveGoodsListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/SendGoodsList",
      component: "./Workstand/Order/Goods/SendGoodsListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/InvoiceList",
      component: "./Workstand/Order/Ticket/InvoiceListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/InvoicingList",
      component: "./Workstand/Order/Ticket/InvoicingListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/OrderManageList",
      component: "./Workstand/Order/Contract/OrderManageListView",
      hideInMenu: true,
      layout: false,
    },
    {
      name: " ",
      path: "/Workstand/OrderDetail",
      component: "./Workstand/Order/Contract/OrderDetailView",
      hideInMenu: true,
      layout: false,
    },
  ],
});
